using EjemploRelevamiento;
Console.Write("Ingresar nombre completo:");
string nombreCompleto=Console.ReadLine();
Console.Write("Ingresar la dirección :");
string direccion = Console.ReadLine();
Console.Write("Ingresar el telefono:");
int telefono = Console.ReadLine();
Console.Write("Ingresar correo :");
string correo = Console.ReadLine();
Console.Write("Ingresar nombre del servicio:");
string nombre = Console.ReadLine();
Console.Write("Ingresar descripcion:");
string descripcion = Console.ReadLine();
Console.Write("Ingresar duracionAproximada :");
int duracionAproximada = Console.ReadLine();
Console.Write("Ingresar el costo:");
decimal costo = Console.ReadLine();
Console.Write("Ingresar la ReservaAnticipada :");
bool RequiereReservaAnticipada = Console.ReadLine();
Console.Write("Ingresar la fecha y hora :");
datetime fechaHora = Console.ReadLine();
Console.Write("Ingresar el nombre :");
string nombre = Console.ReadLine();
Console.Write("Ingresar la especie:");
string especie = Console.ReadLine();
Console.Write("Ingresar la raza :");
string raza = Console.ReadLine();
Console.Write("Ingresar la edad :");
int edad = Console.ReadLine();
Console.Write("Ingresar el peso:");
double peso = Console.ReadLine();
Console.Write("Ingresar el historial de vacunas :");
string historialVacunas = Console.ReadLine();
Console.Write("Ingresar la condicion medica:");
string condicionMedica = Console.ReadLine();
Console.Write("Ingresar el nombre completo del profecional:");
string nombreCompleto = Console.ReadLine();
Console.Write("Ingresar el numero de matricula :");
string numeroMatricula = Console.ReadLine();


